<template>  <view class="page">    <!-- 输入区 -->    <view class="input-row">      <input class="input" v-model.trim="newText"             placeholder="请输入待办事项" @confirm="addTodo" />      <button type="primary" size="mini" @click="addTodo">添加</button>    </view>    <!-- 顶部三 Tab -->    <view class="tabs">      <view class="tab" :class="{ active: currentTab === 'all' }"            @click="currentTab = 'all'">全部</view>      <view class="tab" :class="{ active: currentTab === 'active' }"            @click="currentTab = 'active'">进行中</view>      <view class="tab" :class="{ active: currentTab === 'done' }"            @click="currentTab = 'done'">已完成</view>    </view>

	<!-- 列表：渲染的是 currentList（由 computed 算出来） -->    <view class="list">      <view class="item" v-for="item in currentList" :key="item.id"            @click="item.done = !item.done">        <text :class="{ done: item.done }">{{ item.text }}</text>        <button size="mini" type="warn"                @click.stop="deleteItem(item.id)">删除</button>      </view>    </view>    <!-- 三种空态文案，用 v-if / v-else-if 分支 -->    <view v-if="currentList.length === 0" class="empty">      <text v-if="currentTab === 'all'">还没有待办，添加一条吧</text>      <text v-else-if="currentTab === 'active'">太棒了，没有进行中的事</text>      <text v-else>还没有完成的事，加油</text>    </view>    <!-- 底部固定栏 -->    <view class="bottom-bar">      <text class="count">剩余 {{ unDoneCount }} 项</text>      <text class="clear" @click="clearDone">清除已完成</text>    </view>  </view></template>

<script setup>import { ref, computed, watch } from 'vue'// 数据：只存这一份const list = ref([])            // 本案例升级为 ref，可整体替换const newText = ref('')const currentTab = ref('all')   // 'all' | 'active' | 'done'let nextId = 1// 派生状态：全部由 list 算出来，不另存const activeList = computed(() =>  list.value.filter(t => !t.done))const doneList   = computed(() =>  list.value.filter(t => t.done))const currentList = computed(() => {  if (currentTab.value === 'active') return activeList.value  if (currentTab.value === 'done')   return doneList.value  return list.value})const unDoneCount = computed(() => activeList.value.length)// 副作用：list 一变就落盘（只存，不改 list）watch(list, (val) => {  uni.setStorageSync('todo-list', JSON.stringify(val))}, { deep: true })

// 添加：判空 → push → 清空输入框function addTodo() {  const text = newText.value  if (!text) return uni.showToast({ title: '请输入内容', icon: 'none' })  list.value.push({ id: nextId++, text, done: false })  newText.value = ''}// 删除单条：ref 可以直接整体替换function deleteItem(id) {  list.value = list.value.filter(t => t.id !== id)}// 切换完成：改的是对象属性，视图自动更新// 模板里直接写 @click="item.done = !item.done"// 需要额外逻辑时才包成方法// function toggleDone(item) {//   item.done = !item.done// }

// 清除已完成：先判空，再二次确认function clearDone() {  if (doneList.value.length === 0)    return uni.showToast({ title: '没有可清除的', icon: 'none' })  uni.showModal({    title: '确认清除',    content: `将删除 ${doneList.value.length} 条已完成事项`,    success: (res) => {      if (!res.confirm) return    // 取消则什么都不做      list.value = list.value.filter(t => !t.done)      uni.showToast({ title: '已清除', icon: 'success' })    }  })}</script>

<style scoped>.page { padding: 30rpx; padding-bottom: 140rpx; }  /* 给底部栏留位 */.input-row { display: flex; align-items: center; }.input {  flex: 1; height: 72rpx; padding: 0 20rpx; font-size: 28rpx;  border: 1px solid #DDDDDD; border-radius: 8rpx;}.tabs { display: flex; margin-top: 30rpx; border-bottom: 1px solid #EEEEEE; }.tab { flex: 1; text-align: center; padding: 24rpx 0;       font-size: 28rpx; color: #666666; }.tab.active { color: #2683C6; font-weight: bold;              border-bottom: 4rpx solid #2683C6; }.item { display: flex; align-items: center; justify-content: space-between;        padding: 28rpx 20rpx; margin-top: 20rpx;        background: #FFFFFF; border-radius: 10rpx; }.done { text-decoration: line-through; color: #999999; }.empty { padding: 120rpx 0; text-align: center;         font-size: 28rpx; color: #999999; }.bottom-bar {                      /* 底部固定栏 */  position: fixed; left: 0; right: 0; bottom: 0;  display: flex; justify-content: space-between; align-items: center;  padding: 24rpx 40rpx; background: #FFFFFF; border-top: 1px solid #EEEEEE;}.count { font-size: 28rpx; color: #335B74; }.clear { font-size: 28rpx; color: #D9480F; }</style>

